---
title: "Homework 7"
author: "Your Name Here"
subtitle: "Spring 2023"
header-includes:
    - \usepackage{amsmath}
    - \usepackage{amsthm}
output: pdf_document
---

```{r setup, include=FALSE}
#Use this code chunk to include libraries, and set global options.

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
options(pillar.sigfig=6)

```

### Instructions

- This homework is due in Gradescope on Wednesday May 24 by midnight PST.

- Please answer the following questions in the order in which they are posed. 

- Don't forget to knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope. 


* * *

\textbf{Please note: Hints have been given on several problems. This is to encourage you to problem solve on your own. }

### Exercises

1. (Binomial-Poisson hierarchical model)  The number of eggs, $X$, laid by an insect is a random variable which is often taken to be $Pois(\lambda_0)$. That is, the marginal distribution of $X$ is
\begin{align*}
P(X = x)  &= \frac{ \lambda_0^x e^{-\lambda_0} }{x!}, \ x=0,1,2,\dots
\end{align*}

   Furthermore, if we let $Y=\mbox{number of survivors}$, a common modeling assumption is that given that there are $x$ eggs laid, $Y$ is a binomial random variable. In other words: 
\begin{align*}
P(Y = y | X = x) &= Binom(x, \pi_0)
\end{align*}
where $\pi_0$ is the unknown probability of survival.

a. Derive the joint PMF $f(x,y) = P(X=x, Y=y)$ showing your steps. Don't forget to state the possible values of $x$ and $y$ - these define the range of values for which the joint is non-zero. 

b. Find $P(Y=y)$, the marginal PMF of $Y$. Is it a familiar distribution?  State the values of the parameter(s) of the distribution.

   - you will sum the joint distribution over $x$ (think about the values you will sum over)
  
   - you will make a change of variable $u = x - y$ in the summation
  
c. On the average, how many eggs will survive? That is, what is $E\left[Y\right]$ and why does the answer make sense intuitively?

2. (Normal tolerance) Suppose we sample $X$ from a Normal distribution with mean 0 and tolerance $\tau = \frac{1}{\sigma^2}$. In the Bayesian context, we treat $\tau$ as a random variable.

a. Write the PDF of $X$ indexed by $\tau_0$, a specific value for $\tau$. We think of this as the conditional density of $X$ given $\tau = \tau_0$. (Hint: write the usual Normal PDF but re-parametrized in terms of $\tau$, not $\sigma$.)

b. Suppose we assume $\tau$ is a Gamma random variable, that is our prior distribution is $g(\tau_0) = Gamma(\alpha_0, \lambda_0)$\footnote{see Definition 13.5 in the NOTES} where $\alpha_0$ is the shape and $\lambda_0$ is the rate parameter. Determine the form of the posterior distribution $h(\tau_0|x)$. Is it a familiar distribution? State the values for the parameters of the distribution.

3. (False Discovery) Are many medical discoveries actually Type 1 errors? In medical research, suppose that 10% of null hypotheses are actually false, and that when a null hypothesis is false, the chance of making a Type II error and failing to reject it (for example, due to insufficient sample size) is 0.55.

   a. Given that we reject a null hypothesis at level $\alpha = 0.05$, use Bayes' Rule to show that 50% of such studies are actually reporting Type I errors.  (Please look up chapter 20 in the NOTES for definitions of Type 1 and Type 2 errors.)
   
   \emph{Hints:}
   
   - Define events $H$: "null is false"  and $D$: "do not reject the null". 
   - You are given various probabilities. For example, $P(H) = 0.1$.
   - The level of significance $\alpha$ is the Type 1 error rate of the significance test. That is, it is the conditional probability $P(D^c|H^c)$.
   - You want to calculate $P(H^c|D^c)$. That is, of all the times when you reject the hypothesis, how often is the null actually true?
   
   
  b. The probability you found in a. is called a \emph{False Discovery Rate (FDR)}. Your calculation shows that even though we control the Type 1 error rate at 0.05, the FDR can be high. 
   
   Write a function in R to perform the FDR computation in part a. which takes as input: the probability of $H$, the Type 1 and Type 2 error rates, and calculates the FDR. Then run it for all combinations of the following inputs:
  
  - $P(H)$: 0.05, 0.1, 0.2, 0.5
  
  - Type 1 error rate: 0.0001, 0.005, 0.01, 0.05
  
  - Type 2 error rate: 0.05, 0.2, 0.3, 0.5
  
    Make a table of the resulting FDRs, and write a few sentences summarizing what you observe. Conclude your summary with practical advice for the data scientist who is wondering how to choose their $\alpha$ level for a significance test.   (You can manually supply all the combinations of inputs to your function, or check out `expand_grid` to generate a data frame with one row for each combination of the inputs.  See `simulating-a-poisson-process.Rmd` from STAT 340 which I have pushed to your HW folder.)
  

  
4. Before a U.S. Presidential election, polls are taken in two swing states. The Republican candidate was preferred by 59 out of the 100 people sampled in state A and by 525 out of 1,000 sampled in state B.  

a. If we can treat these polls as if the samples were randomly drawn from the population with a proportion $\pi$ voting Republican, use a large sample Z test of $H_0: \pi = 0.5$ versus $H_1: \pi > 0.5$ to determine which state has greater evidence supporting a Republican victory.  Show your work.

b. Conduct a Bayesian analysis to answer the question in part a. by finding in each case the posterior probability of the null hypothesis: $P(\pi \leq 0.5)$. Use a beta prior which has mean 0.5 and standard deviation 0.05. Explain any differences between conclusions. (This is an open ended question)