---
title: "Problem Section 2"
subtitle:  "The sample variance and chi square distribution"
graphics: yes
output: pdf_document
header-includes: 
- \usepackage{amssymb, amsmath, amsfonts}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


### Exercises 

1. Suppose $\mathbf{x} = \langle 3, 4,5, 8 \rangle$ and consider the basis defined by 

- $\mathbf{u}_1 = \frac{1}{\sqrt{4} } \langle 1,1,1,1, \rangle$

- $\mathbf{u}_2 = \frac{1}{\sqrt{2} } \langle 1, -1, 0, 0 \rangle$

- $\mathbf{u}_3 = \frac{1}{\sqrt{6}} \langle 1, 1, -2,  0 \rangle$

- $\mathbf{u}_4 = \frac{1}{\sqrt{12 }} \langle 1, 1,1, -3\rangle$


  a.  Determine (by hand and then verify using `project` in \textbf{mosaic}) the coordinates $P_i$ of $\mathbf{x}$ with respect to the basis vectors $\left\{\mathbf{u}_1, \mathbf{u}_2, \mathbf{u}_3, \mathbf{u}_4 \right\}$. 
  
  b. Verify that $$\mathbf{x} = \sum\limits_{i=1}^{4} P_i \mathbf{u}_i.$$ 

  c.  Calculate the sample variance $s^2$ using R for this dataset. Then verify that $3\:s^2= P^2_2 + P^2_3 + P^2_4$.
 
2. A stock analyst claims to have devised a mathematical technique for selecting high-quality mutual funds
and promises that a client’s portfolio will have higher average ten-year annualized returns and lower volatility; that
is, a smaller standard deviation. After ten years, one of the
analyst’s twenty-four-stock portfolios showed a standard deviation of 10.17%. The benchmarks for the type of funds
considered are a standard deviation
of 15.67%.

a. Let $\sigma_0$ be the standard deviation for a twenty-four stock portfolio selected by the analyst’s method. Calculate a 95% confidence interval for $\sigma_0$. 

b. Do you think the assumptions underlying the confidence interval from part a are valid? If not, which ones might be violated?
 
3. If a 90\% confidence interval for $\sigma^2_0$ is reported to be $[51.47, 261.90]$, what is the value of the sample variance $s^2$? 
  