---
title: "Problem Section 4"
subtitle:  "Likelihood function and MLEs"
graphics: yes
output: pdf_document
header-includes: 
- \usepackage{amssymb, amsmath, amsfonts}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Exercises 


1. A positive continuous random variable X has density 
$$f(x) = \theta_0 \frac{1}{(1+x)^{\theta_0+1}} \ \ x \geq 0$$
where $\theta_0$ is known to be 2,3 or 4.
Given two independent observations of $X$ with values 0.2 and 0.8,

a. Find the likelihood function $L(\theta)$.

b. Determine $\widehat{\theta}_0^{mle}$, the MLE of $\theta$.

2. Suppose $X_1, X_2, \dots, X_n$ are independent random variables with PMF
\begin{eqnarray*}
f(x) &=& \left\{ \begin{array}{cc}
             \frac{1}{3} - \theta_0 & x = 0  \\
             \frac{1}{3} & x =1 \\
             \frac{1}{3} + \theta_0 & x =2 \end{array} \right.
\end{eqnarray*}
where you can assume $-\frac{1}{3} \leq \theta_0 \leq \frac{1}{3}$ so all probabilities are non-zero.

a. Based on the sample 0, 0, 1, 0, 1, 2, 1, 0, 0, write an expression for the likelihood function $L(\theta)$. 

b. Make a plot of the likelihood function $L(\theta)$ and also of $\ell = \ln(L(\theta))$. 

c. Calculate $\widehat{\theta}_0^{mle}$, the MLE of $\theta_0$.

3. A company has manufactured certain objects and has printed a serial number on each manufactured object. The serial numbers start at 1 and end at $N$, where $N$ is the (unknown) number of objects that have been manufactured. One of these objects is selected at random, and the serial number of that object is 888.

a. What is the method of moments estimate of $N$?  Don't forget to:
  - Define the random variable $X$
  - Write the PMF of $X$
  - Calculate $E\left[X \right]$ with your work shown
  - Give the method of moments estimate

b. What is the maximum likelihood estimator of $N$? Don't forget to:
  - Write the likelihood function
  - Maximize it to find the MLE
  
  
4. Suppose 100 seeds are planted and it is known only that $x \leq 15$ seeds germinated. That is, the exact number of germinating seeds is not known. Let $\pi$ denote the probability that a randomly selected seed will germinate. How would you define the likelihood function $L(\pi)$ in this situation?
